### ISSUE TITLE
Bubble diagram "üres" évre is kirakja a vizsgált település értékét

### ISSUE THREAD

**Issue by Zsott** [Zsott/Dash-Map-Board#7]
Ha a timeStops array-t egy olyan évvel bővítjük, amelyre nincs adat (pl. 2018), akkor a bubble-nél megjelenik egy buborék (vszeg a legfrissebb év adataival??).

**Comment by Zsott** [comment]
Tök jó, amit eddig csináltál, de **sajnos** majdnem több problémát vetett fel, mint amennyit megoldott.

Ezért inkább tegyük bele a config validator-ba ennek az ellenőrzését.
Az ArcGISDynamicMapServiceLayer-nek van egy timeInfo property-je., ami visszaad egy TimeInfo objectet. Ennek van egy timeExtent property-je, amid visszaad egy TimeExtent objectet. Ennek pedig van egy endTime és egy startTime property-je. Ezekkel tudjuk majd validálni, hogy a timeStops config minden eleme nagyobb-egyenlő-e a startTime-nál és kisebb-egyenlő-e az endTime-nál.
Itt valószínűleg a dátum formátumra kell figyelnünk a validálás során.

**Comment by lelleil** [comment]
Igen, de majd figyelni kell, ha olyan az időtudatos réteg, akkor figyeljünk a valós geometriára és az adott évhez tartozó geometriát jelöljük ki és a hozzá tartozó területegység nevét írjuk ki.

**Comment by Zsott** [comment]
Laca megoldotta. Köszi!
